Yeji week18
algorithm-cote-study/baekjoon-algorithm pull request #13
Opened 2023-05-14 00:12 UTC by cyeji

2023-05-14 11:35 UTC, songjuAhn commented on src/main/java/org/backjoon/class3/yeji/Main5430.java
> +        return answer + "\n";
+로 연결하기보단 append하고 toString으로 변환해서 리턴해주는게 좋을 것 같아요

2023-05-15 06:34 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main5430.java
> +        return answer + "\n";
넵 수정했습니다 :)

2023-05-15 06:43 UTC, songjuAhn approved these changes

2023-05-15 13:45 UTC, seunggulee1007 requested changes

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main1918.java
> +                    while (stack.peek() != null && '(' != stack.peek()) {
stack.peek()가 null인지 확인하시는거 보다 이 경우에는 stack이 비었는지 확인하는 것이 더 바람직 합니다.
따라서 stack.isEmpty()를 확인해 보시는 걸 추천합니다.

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main1927.java
> +        PriorityQueue<Integer> pQ = new PriorityQueue<>();
변수는 최대한 알아볼 수 있도록 적어 주시는 것이 좋습니다.
그리고 PriorityQueue는 Queue로 받을 수 있습니다.

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main1927.java
> +                answer.append(pQ.isEmpty() ? "0\n" : pQ.poll() + "\n");
\n이 반복적으로 들어간다면 삼항연산자에서 0 또는 poll()하신 것을 넣고 그 뒤에 append("\n")을 하시는 것이 좋습니다.

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main1927.java
> +        while (n > 0) {
n번 만큼 반복문이 돌아야 한다면 for문을 사용하시는 것이 직관적입니다.

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main5430.java
> +        while (n > 0) {
for문을 사용하시는 것이 더 직관적이고 가독성이 좋을 것으로 보입니다.

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main7662.java
> +                    Integer key = "1".equals(input[1]) ? treeMap.lastKey() : treeMap.firstKey();
Integer를 사용한 이유가 있을까요?
wrapper클래스를 사용한 이유가 궁금하네요

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class4/yeji/Main11286.java
> +        while (n > 0) {
for 문이 좀 더 가독성이 좋습니다.

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class4/yeji/Main11286.java
> +        return priorityQueue.isEmpty() ? "0\n" : priorityQueue.poll() + "\n";
3항 연산자로 0, poll() 하고 마지막에 \n을 해 주세요

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class4/yeji/Main1717.java
> +        int[] input = Arrays.stream(br.readLine().split(" ")).mapToInt(Integer::parseInt).toArray();
변수 명 신경 써 주세요

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class4/yeji/Main1717.java
> +        return find(a) != find(b) ? "NO\n" : "YES\n";
맨 뒤에 \n 변경 해 주세요

2023-05-15 13:45 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class4/yeji/Main1918.java
> +                    while (stack.peek() != null && '(' != stack.peek()) {
stack.peek()이 null인지 확인하는 것 보다 stack.isEmpty()를 확인하시는 게 더 좋습니다.

2023-05-15 13:52 UTC, seunggulee1007 requested changes

2023-05-15 13:52 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main5430.java
> +            Integer.parseInt(br.readLine());
이 코드는 사용을 하지 않는 코드인데 불필요하게 형변환 할 필요가 없어 보이네요

2023-05-15 14:01 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main5430.java
> +            Integer.parseInt(br.readLine());
형변환 제거 했습니다

2023-05-15 14:03 UTC, cyeji commented on src/main/java/org/backjoon/class4/yeji/Main1918.java
> +                    while (stack.peek() != null && '(' != stack.peek()) {
넵 수정했습니다

2023-05-15 14:05 UTC, cyeji commented on src/main/java/org/backjoon/class4/yeji/Main1717.java
> +        return find(a) != find(b) ? "NO\n" : "YES\n";
whiteSpace는 메소드 호출시 append하도록 분리했습니다.

2023-05-15 14:08 UTC, cyeji commented on src/main/java/org/backjoon/class4/yeji/Main1717.java
> +        int[] input = Arrays.stream(br.readLine().split(" ")).mapToInt(Integer::parseInt).toArray();
변수명 변경했습니다.

2023-05-15 14:10 UTC, cyeji commented on src/main/java/org/backjoon/class4/yeji/Main11286.java
> +        return priorityQueue.isEmpty() ? "0\n" : priorityQueue.poll() + "\n";
메소드 호출 후 whitespace append하도록 분리했습니다.

2023-05-15 14:11 UTC, cyeji commented on src/main/java/org/backjoon/class4/yeji/Main11286.java
> +        while (n > 0) {
넵 변경했습니다

2023-05-15 14:12 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main5430.java
> +        while (n > 0) {
넵 변경했습니다.

2023-05-15 14:17 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main1927.java
> +        while (n > 0) {
넵 변경했습니다.

2023-05-15 14:17 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main1927.java
> +                answer.append(pQ.isEmpty() ? "0\n" : pQ.poll() + "\n");
넵 변경했습니다.

2023-05-15 14:18 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main1927.java
> +        PriorityQueue<Integer> pQ = new PriorityQueue<>();
넵 변경했습니다.

2023-05-15 14:18 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main1918.java
> +                    while (stack.peek() != null && '(' != stack.peek()) {
넵 변경했습니다.

2023-05-16 14:35 UTC, seunggulee1007 approved these changes

2023-05-16 14:35 UTC, merged