Seunggu/class3
algorithm-cote-study/baekjoon-algorithm pull request #15
Opened 2023-05-15 13:14 UTC by seunggulee1007

2023-05-15 13:31 UTC, cyeji requested changes
이번에 문제 푼 갯수에 비해 테스트 코드가 적네요

2023-05-15 13:31 UTC, cyeji commented on src/main/java/org/backjoon/class2/seunggu/Main1764.java
> +        if (integer == 1) {
불필요한 조건문은 제거해주세요.

2023-05-15 13:31 UTC, cyeji commented on src/main/java/org/backjoon/class2/seunggu/Main1764.java
> +public class Main1764 {
문제 명 명시해주셨으면 좋겠어요

2023-05-15 13:32 UTC, cyeji requested changes
이번에 문제 푼 갯수에 비해 테스트 코드가 적네요

2023-05-15 13:32 UTC, cyeji requested changes
이번에 문제 푼 갯수에 비해 테스트 코드가 적네요

2023-05-15 13:32 UTC, cyeji requested changes
이번에 문제 푼 갯수에 비해 테스트 코드가 적네요

2023-05-15 13:32 UTC, cyeji requested changes
이번에 문제 푼 갯수에 비해 테스트 코드가 적네요

2023-05-15 13:32 UTC, cyeji requested changes
이번에 문제 푼 갯수에 비해 테스트 코드가 적네요

2023-05-15 13:57 UTC, cyeji commented on src/main/java/org/backjoon/class3/seunggu/Main1918.java
> +        switch (word) {
case 분기마다 return 문 작성하는 것보단 switch 문에서 값을 바로 return 해주면 좋을 것 같아요

```java

return switch (word) {
            case "(", ")" -> 1;
            case "+", "-" -> 2;
            case "*", "/" -> 3;
            default -> 0;
        };

```

2023-05-15 14:38 UTC, cyeji commented on src/main/java/org/backjoon/class3/seunggu/Main1003.java
> +        return dp[num];
0번째 인덱스의 값이 무조건 append되는 거라면 return 값을 int로 바꿔줘도 될 것 같아요

2023-05-15 14:38 UTC, cyeji commented on src/main/java/org/backjoon/class3/seunggu/Main1717.java
> +        return unf[v];
저는 inline변수로 만들어서 사용했는데 분리하니 가독성이 더 좋네요 👍

2023-05-16 10:58 UTC, songjuAhn approved these changes

2023-05-16 14:29 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/seunggu/Main1003.java
> +        return dp[num];
배열을 넘긴다음에 0번째랑 1번째 둘다 꺼낸답니다  😃

2023-05-16 14:29 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/seunggu/Main1717.java
> +        return unf[v];
👍🏻

2023-05-16 14:30 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/seunggu/Main1918.java
> +        switch (word) {
네 그렇게 하니까 더 좋네요 👍🏻

2023-05-16 14:30 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class2/seunggu/Main1764.java
> +public class Main1764 {
문제명 명시 해서 올렸습니다 !

2023-05-16 14:30 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class2/seunggu/Main1764.java
> +        if (integer == 1) {
제거 했습니다!

2023-05-16 14:33 UTC, cyeji approved these changes

2023-05-16 14:33 UTC, merged