2023Y 19W YEJI
algorithm-cote-study/baekjoon-algorithm pull request #16
Opened 2023-05-21 03:47 UTC by cyeji

2023-05-21 07:46 UTC, songjuAhn approved these changes

2023-05-21 07:46 UTC, songjuAhn commented on src/main/java/org/backjoon/class5/Main1520.java
> +        public int compareTo(Node node) {
이 부분은 사용되는 곳이 없어보이는데 삭제하면 좋을 것 같아요

2023-05-22 07:29 UTC, cyeji commented on src/main/java/org/backjoon/class5/Main1520.java
> +        public int compareTo(Node node) {
Node객체는 prioirtyQueue에서 우선순위를 결정지을 수 없기 때문에 Comparable의 메소드 compareTo를 직접 구현해 Node객체의 우선순위를 결정해주기 위해서 사용하였습니다. 그래서 직접 사용되는 곳은 없지만 priorityQueue에서 내부적으로 활용되고 있습니다!

2023-05-23 00:33 UTC, songjuAhn commented on src/main/java/org/backjoon/class5/Main1520.java
> +        public int compareTo(Node node) {
그렇군요! 하나 배워갑니다!

2023-05-23 09:43 UTC, seunggulee1007 requested changes

2023-05-23 09:43 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class5/yeji/Main1260.java
> +    private static int[] dfs;
dfs , bfs 가 함수명이랑 겹치네요

2023-05-23 09:43 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class5/yeji/Main1463.java
> +        int key;
캡슐화를 지켜 주세요.

2023-05-23 09:43 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class5/yeji/Main1520.java
> +        int x;
캡슐화를 지켜 주세요.

2023-05-23 09:43 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class5/yeji/Main15486.java
> +        int requiredDays;
캡슐화를 지켜 주세요

2023-05-24 06:43 UTC, cyeji commented on src/main/java/org/backjoon/class5/yeji/Main1260.java
> +    private static int[] dfs;
전역변수에 선언된 dfs, bfs는 사용되지 않는 변수라 제거했습니다.

2023-05-24 06:43 UTC, cyeji commented on src/main/java/org/backjoon/class5/yeji/Main1463.java
> +        int key;
수정했습니다.

2023-05-24 06:43 UTC, cyeji commented on src/main/java/org/backjoon/class5/yeji/Main1520.java
> +        int x;
수정했습니다.

2023-05-24 06:43 UTC, cyeji commented on src/main/java/org/backjoon/class5/yeji/Main15486.java
> +        int requiredDays;
수정했습니다.

2023-05-24 06:49 UTC, seunggulee1007 approved these changes
확인 됐습니다
고생하셨습니다.

2023-05-24 06:49 UTC, merged