Yeji week23
algorithm-cote-study/baekjoon-algorithm pull request #28
Opened 2023-06-18 11:24 UTC by cyeji

2023-06-19 10:53 UTC, songjuAhn commented on src/main/java/org/backjoon/class9/yeji/Main11559.java
> +                    if (!visited[cx][cy] && map[cx][cy].equals(cur.color)) {
조건문을 합쳐서 한줄로 하면 좋을 것 같아요

2023-06-20 02:39 UTC, cyeji commented on src/main/java/org/backjoon/class9/yeji/Main11559.java
> +                    if (!visited[cx][cy] && map[cx][cy].equals(cur.color)) {
넵 변경했습니다.

2023-06-20 12:05 UTC, seunggulee1007 requested changes

2023-06-20 12:05 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class9/yeji/Main1459.java
> +        long case2 = (input[0] + input[1]) % 2 == 0 ? case1(input[0], input[1], input[3]) : case2(input[0], input[1], input[2], input[3]);
메서드 명과 변수명은 헷갈릴 수 있으니 동일하게 작성하는 것을 지양해 주시기 바랍니다.

2023-06-21 04:11 UTC, cyeji commented on src/main/java/org/backjoon/class9/yeji/Main1459.java
> +        long case2 = (input[0] + input[1]) % 2 == 0 ? case1(input[0], input[1], input[3]) : case2(input[0], input[1], input[2], input[3]);
수정했습니다.

2023-06-21 10:29 UTC, songjuAhn approved these changes

2023-06-22 05:11 UTC, seunggulee1007 approved these changes
수고하셨습니다.

2023-06-22 05:11 UTC, merged