Yeji
algorithm-cote-study/baekjoon-algorithm pull request #9
Opened 2023-05-07 05:16 UTC by cyeji

2023-05-07 05:48 UTC, seunggulee1007 requested changes

2023-05-07 05:48 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main16236.java
> +    private static int[] cur = new int[2];
전역변수 초기화는 신경써서 해 주셔야 합니다.
전역변수는 모든 인스턴스에서 공유 하므로, 인스턴스가 생성되고 가비지 컬렉터에 의해 사라지기 전 까지 인스턴스가 새로 생성될 일 없을 경우에만 전역변수에 초기화를 넣어주시는 게 좋습니다.
아니라면 main 함수 등에서 초기화를 해 주셔야 합니다.

2023-05-07 05:48 UTC, seunggulee1007 commented on src/main/java/org/backjoon/class3/yeji/Main2630.java
> +            for ( int s : solution( br ) ) {
변수를 만드실 때 신경 써 주세요.
심지어 int인데 s인 것은 일관성 면에서도 문제가 되어 보입니다.

2023-05-08 01:25 UTC, songjuAhn commented on src/main/java/org/backjoon/class3/yeji/Main2579.java
> +    static int findMaxStair ( int n ) {
메서드 리턴형이 의미가 없어보여요. void로 변경하는게 좋을 것 같아요

2023-05-08 01:33 UTC, songjuAhn commented on src/main/java/org/backjoon/class3/yeji/Main2579.java
> +    static int findMaxStair ( int n ) {
메서드 리턴형이 의미가 없어보여요. void로 변경하는게 좋을 것 같아요

2023-05-08 02:08 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main16236.java
> +    private static int[] cur = new int[2];
전역변수 초기화 위치를 메소드 호출시 초기화 되도록 변경했습니다 :)

2023-05-08 02:08 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main2630.java
> +            for ( int s : solution( br ) ) {
메소드 명 앞자에서 따온 변수명이였는데 그 부분까지는 미처 생각하지 못했네요 수정했습니다 :)

2023-05-08 02:09 UTC, cyeji commented on src/main/java/org/backjoon/class3/yeji/Main2579.java
> +    static int findMaxStair ( int n ) {
void로 변경했습니다 :)

2023-05-08 08:43 UTC, seunggulee1007 approved these changes

2023-05-10 00:18 UTC, songjuAhn approved these changes

2023-05-10 01:10 UTC, merged